"$schema" = 'https://starship.rs/config-schema.json'

right_format = """[](fg:start)$time[](fg:start)"""

continuation_prompt = '▶▶ '


format = """
[ ♡](bg:#e2bef1 fg:#101010)\
$username\
[](bg:middle fg:start)\
$directory\
[](fg:middle bg:middle2)\
$git_branch\
[･✧:･](bg:middle2 fg:#101010)\
[ ](fg:middle2 bg:middle3)\
$c\
${custom.cpp}\
${custom.makefile}\
$java\
${custom.lua}\
${custom.vimrc}\
${custom.js}\
${custom.py}\
$character \
"""





#palette = 'purple'
#palette = 'vaporwave'
#palette = 'retro'
#palette = 'engine'
#palette = 'retrorainbow'
#palette = 'veryred'
#palette = 'last_purple'
palette = 'cute'

[palettes.cute]
start = '#e2bef1'
middle = '#f5cdde'
middle2 = '#c6f8e5'
middle3 = '#e2bef1'
error = '#ff00f7'
text = '#FFFFFF'

[palettes.last_purple]
start = '#5E008A'
middle1 = '#7A00B3'
middle2 = '#9D00E5'
middle3 = '#AE00FF'
error = '#ff00f7'
text = '#FFFFFF'

[palettes.veryred]
start = '#CE0000'
middle1 = '#AA0000'
middle2 = '#D5D5D5'
middle3 = '#F1F1F1'
error = '#FFDFD3'
text = '#032323'

[palettes.retrorainbow]
start = '#b25da6'
middle1 = '#6688c3'
middle2 = '#48a56a'
middle3 = '#eaaf41'
error = '#FFDFD3'
text = '#ffffff'

[palettes.engine]
start = '#D52429'
middle1 = '#F1602C'
middle2 = '#EC8922'
middle3 = '#915018'
error = '#FFDFD3'
text = '#f5f5f5'

[palettes.retro]
start = '#01204E'
middle1 = '#028391'
middle2 = '#F85525'
middle3 = '#FAA968'
error = '#FFDFD3'
text = '#f5f5f5'

[palettes.vaporwave]
start = '#ff00c1'
middle1 = '#9600ff'
middle2 = '#4900ff'
middle3 = '#00b8ff'
error = '#FFDFD3'
text = '#f5f5f5'

[palettes.rad]
start = '#e2bef1'
middle = '#f5cdde'
middle2 = '#c6f8e5'
middle3 = '#e2bef1'
error = '#ff00f7'
text = '#FFFFFF'

[palettes.purple]
start = '#E0BBE4'
middle1 = '#957DAD'
middle2 = '#D291BC'
middle3 = '#FEC8D8'
error = '#FFDFD3'
text = '#000000'


[java]
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[custom.js]
detect_extensions = ['js']
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[c]
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[custom.vimrc]
detect_extensions = ['vimrc']
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[custom.lua]
detect_extensions = ['lua']
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'


[custom.makefile]
detect_files = ['Makefile', 'makefile']
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[custom.py]
detect_extensions = ['py']
symbol = ' '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[custom.cpp]
detect_extensions = ['cpp', 'hpp']
symbol = '󰙲 '
style = 'fg:text bg:middle3'
format = '[ $symbol]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[ $time ☭ ](bg:start fg:#101010)]($style)'

[git_status]
format = '[$all_status $ahead_behind]($style)'
up_to_date = '✓'
conflicted = '🏳'
ahead = '⇑'
behind = '⇓'
diverged = '↰'
untracked = ' 󰤔'
stashed = ' 🮽'
modified = ' ⚙'
staged = '[++\($count\)](fg:text bg:middle2)'
renamed = '✎'
deleted = '🗑 '
style = "fg:text bg:middle2"

[git_branch]
style = "bg:#middle2"
format = '[[ ✄ $branch ](fg:#101010 bg:middle2)]($style)'


[username]
disabled = false
show_always = true
style_user = 'fg:#101010 bg:start'
format = '[ Ｐａｔｚイン ]($style)'

[hostname]
style = 'fg:text bg:start'
format = '[ $hostname]($style)'
ssh_only = false
disabled = false

[character]
success_symbol = '[](middle3)'
error_symbol = '[](error)'

[directory]
format = '[  $path]($style)'
style = 'fg:#101010 bg:middle'
truncation_length = 1
truncation_symbol = "凹"

[os]
format = '[$symbol ]($style)'
disabled = false
style = 'fg:text bg:start'

[os.symbols]
Windows = "󰍲"
Ubuntu = ""
SUSE = ""
Raspbian = ""
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

